server {
	listen 443 ssl;
	server_name ${DOMAIN_NAME};

	ssl_certificate /var/lib/lego/certificates/${DOMAIN_NAME}.crt;
	ssl_certificate_key /var/lib/lego/certificates/${DOMAIN_NAME}.key;

	root /var/www/application/;
	index index.html;

	location / {
		try_files $uri $uri/ =404;
	}
}
